-------------------------------------------------- DELETE DATA FROM TABLES --
DELETE FROM TRAN;
DELETE FROM ACCOUNT;


-----  REMOVE EXISTING TABLES ----

ALTER TABLE TRAN DROP CONSTRAINT ACC_TRAN;
DROP TABLE  TRAN;
DROP TABLE  ACCOUNT;

-------------------------------------------------- CREATE TABLES -----

CREATE TABLE ACCOUNT  (

		  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY ,

		  BALANCE DECIMAL(14,2),

		  DESCRIPTION VARCHAR(150) , 
		  
		  USERNAME VARCHAR(50),
		  
		  CURRENCY VARCHAR(8),

		  TYPE_ID INTEGER 
);

CREATE TABLE TRAN  (

		  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY ,
		  ACCOUNT_ID INTEGER NOT NULL,
		  TRAN_TYPE VARCHAR(50),
		  AMOUNT DECIMAL(14,2),
		  DESCRIPTION VARCHAR(150) , 
		  TDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		  MERCHANT VARCHAR(50),
		  CURRENCY VARCHAR(8)
);

ALTER TABLE TRAN ADD CONSTRAINT ACC_TRAN FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID);

INSERT INTO ACCOUNT (BALANCE,DESCRIPTION,USERNAME,TYPE_ID,CURRENCY) VALUES (1000,'Primary Checking','kbrown',1,'USD');
INSERT INTO ACCOUNT (BALANCE,DESCRIPTION,USERNAME,TYPE_ID,CURRENCY) VALUES (1000,'Primary Checking','rbarcia',1,'USD');
INSERT INTO ACCOUNT (BALANCE,DESCRIPTION,USERNAME,TYPE_ID,CURRENCY) VALUES (1000,'Primary Checking','kbishop',1,'USD');
INSERT INTO ACCOUNT (BALANCE,DESCRIPTION,USERNAME,TYPE_ID,CURRENCY) VALUES (1000,'Primary Checking','mperrins',1,'GBP');
INSERT INTO ACCOUNT (BALANCE,DESCRIPTION,USERNAME,TYPE_ID,CURRENCY) VALUES (1000,'Primary Savings','rbarcia',2,'USD');

INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (2,'WITHDRAWL',20,'Purchase','Hallmark Cards','USD');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (1,'WITHDRAWL',100,'WITHDRAWL 100 FROM BANK','TELLER','USD');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (2,'DEPOSIT',200,'DEPOSIT 200 TO ATM','ATM','USD');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (3,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (4,'DEPOSIT',100,'DEPOSIT 100 TO BANK','TELLER','GBP');
INSERT INTO TRAN (ACCOUNT_ID,TRAN_TYPE,AMOUNT,DESCRIPTION,MERCHANT,CURRENCY) VALUES (5,'DEPOSIT',200,'DEPOSIT 200 TO BANK CHECKING','TELLER','USD');



